local currentPath = (...):gsub('%.init$', '') .. "."

require(currentPath .. "label")
require(currentPath .. "button")
require(currentPath .. "slider")
require(currentPath .. "text-field")
require(currentPath .. "checkbox")
require(currentPath .. "radio")
require(currentPath .. "split-view")
require(currentPath .. "divider")
require(currentPath .. "scroll-bar")
require(currentPath .. "clip-view")
require(currentPath .. "scroll-view")
require(currentPath .. "menu-bar")
require(currentPath .. "sub-menu")
require(currentPath .. "menu-item")
require(currentPath .. "progress")
require(currentPath .. "tab-bar")
require(currentPath .. "panel-background")
require(currentPath .. "image")
require(currentPath .. "image-9-slice")
require(currentPath .. "msdf-image")
require(currentPath .. "msdf-image-9-slice")
require(currentPath .. "msdf-layered-image")
require(currentPath .. "msdf-layered-image-9-slice")
